// Generated by CoffeeScript 1.6.2
(function() {
  var InstagramTags;

  InstagramTags = (function() {
    function InstagramTags(parent) {
      this.parent = parent;
    }

    InstagramTags.prototype.info = function(params) {
      var credentials;

      credentials = this.parent._credentials({});
      params['path'] = "/" + this.parent._api_version + "/tags/" + params['name'] + "?" + (this.parent._to_querystring(credentials));
      return this.parent._request(params);
    };

    InstagramTags.prototype.recent = function(params) {
      var to_querystring;

      to_querystring = this.parent._credentials({});
      if (params['min_id'] != null) {
        to_querystring['min_id'] = params['min_id'];
      }
      if (params['max_id'] != null) {
        to_querystring['max_id'] = params['max_id'];
      }
      params['path'] = "/" + this.parent._api_version + "/tags/" + params['name'] + "/media/recent?" + (this.parent._to_querystring(to_querystring));
      return this.parent._request(params);
    };

    InstagramTags.prototype.search = function(params) {
      params = this.parent._credentials(params);
      params['path'] = "/" + this.parent._api_version + "/tags/search?" + (this.parent._to_querystring(params));
      return this.parent._request(params);
    };

    InstagramTags.prototype.subscribe = function(params) {
      params['object'] = 'tag';
      return this.parent.subscriptions._subscribe(params);
    };

    InstagramTags.prototype.unsubscribe = function(params) {
      return this.parent.subscriptions._unsubscribe(params);
    };

    InstagramTags.prototype.unsubscribe_all = function(params) {
      params['object'] = 'tag';
      return this.parent.subscriptions._unsubscribe(params);
    };

    return InstagramTags;

  })();

  module.exports = InstagramTags;

}).call(this);
